-- requires
require "conf.options"
require "conf.lazy"
require "conf.remaps"

-- require "conf.plugins"
-- require 'conf.colorscheme'
-- require "conf.nvim-tree"
-- require "conf.bufferline"
-- require "conf.cmp"
-- require "conf.luasnip"
-- -- require "conf.lsp"
-- require "conf.mason"
-- require "conf.treesitter"
-- require "conf.lualineO"
-- require "conf.telescope"
-- require "conf.telescope-maps"
-- require "conf.alpha"
-- require "conf.autopairs"
-- require "conf.comment"
-- require "conf.gitsigns"
